on:
  push:
    branches: 
      - master
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - master 
    paths-ignore:
      - '.github/workflows/*'   
jobs:
  TestAndDeploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Check linting and formatting
        run: npm run lint

      - name: Test application
        run: npm run test

      - name: Create test build
        run: npm run build
              